# Generated by Django 3.2.3 on 2021-05-19 10:32

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=40, verbose_name='Name')),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=18, unique=True, verbose_name='Farbe')),
                ('point_status', models.IntegerField(verbose_name='Punktestand')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Aenderungsdatum')),
            ],
        ),
    ]
