# Generated by Django 3.2.3 on 2021-05-19 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=40, verbose_name='Name')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Aenderungsdatum')),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='point_status',
            field=models.IntegerField(default=0, verbose_name='Punktestand'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_points', models.IntegerField(choices=[(100, 100), (80, 80), (60, 60), (40, 40), (20, 20)], verbose_name='Punkte')),
                ('name', models.CharField(blank=True, max_length=40, verbose_name='Name')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Aenderungsdatum')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_game.topic')),
            ],
            options={
                'unique_together': {('question_points', 'topic')},
            },
        ),
    ]
