# Generated by Django 3.2.3 on 2021-05-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0002_auto_20210519_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Aktiv?'),
        ),
    ]
