# Generated by Django 3.2.3 on 2021-05-31 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0004_log_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_points',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_game.point'),
        ),
    ]
