# Generated by Django 3.2.3 on 2021-05-31 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0005_alter_question_question_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='action',
            field=models.CharField(choices=[('closed', 'geschlossen'), ('open', 'geöffnet')], default='open', max_length=40, verbose_name='Aktion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Erstellungsdatum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='rollback',
            field=models.BooleanField(default=False, verbose_name='Rückgängig gemacht?'),
        ),
    ]
