# Generated by Django 3.2.4 on 2021-06-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0006_auto_20210531_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_category',
            field=models.CharField(choices=[('Frage', 'Frage'), ('Schätzfrage', 'Schätzfrage'), ('Aktion', 'Aktion'), ('Battle', 'Battle')], default='Frage', max_length=40, verbose_name='Kategorie'),
        ),
        migrations.AddField(
            model_name='question',
            name='solution',
            field=models.CharField(blank=True, max_length=40, verbose_name='Loesung'),
        ),
    ]
