# Generated by Django 3.2.4 on 2021-06-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0007_auto_20210630_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(choices=[('closed', 'geschlossen'), ('open', 'geöffnet')], max_length=240, verbose_name='Aktion'),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(blank=True, max_length=240, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_category',
            field=models.CharField(choices=[('Frage', 'Frage'), ('Schätzfrage', 'Schätzfrage'), ('Aktion', 'Aktion'), ('Battle', 'Battle'), ('Joker', 'Joker')], default='Frage', max_length=40, verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='question',
            name='solution',
            field=models.CharField(blank=True, max_length=240, verbose_name='Loesung'),
        ),
    ]
